declare module "lodash" {
    function head(...): ...
    function hasIn(...): ...
    function isBoolean(...): ...
    function toString(...): ...
    function split(...): ...
    function hasPath(...): ...
    function filter(...): ...
    function every(...n): ...
    function map(...): ...
    }